### ISSUE TITLE
ggstar with subset?

### ISSUE THREAD

**Issue by layka-pacheco** [xiangpin/ggstar#1]
Hello, 

Thanks a lot for the great package. I was wondering if there would be a way to use ggstar with subsetting, something like:

`geom_star(aes(subset = (node == 480)), starshape = 25, size = 1.25, fill = '#44AA99', starstroke = .07, show.legend = FALSE)`

Many thanks in advance, George.

**Comment by xiangpin** [comment]
Yes, This is useful to display the data that meet some conditions. The `github` version has supported it. You can install it via `remotes::install_github("xiangpin/ggstar")`.

**Comment by layka-pacheco** [comment]
Hello, 

Thanks very much for your quick reply.
I can confirm that it does work. Apologies for not noticing it before. 

Best regards, George.
